#!/bin/bash

# Check to see if todo directory exists
if [ ! -d "$HOME/notes/todo" ]
then 
	echo "Error: directory ~/notes/todo does not exist."
	exit
fi

today=$(date +'%m-%d-%Y')

if [ ! -d "$HOME/notes/todo/todo_$today.md" ]
then
	touch $HOME/notes/todo/todo_$today.md
fi

vim $HOME/notes/todo/todo_$today.md

exit
