#!/bin/bash

today_date=$(date +'%m-%d-%Y')
today_path="$HOME/notes/todo/todo_$today.md"
yesterday_date=$(date -v -1d '+%m-%d-%Y')
yesterday_path="$HOME/notes/todo/todo_$yesterday_date.md"

function yesterday {
  if [ ! -f $yesterday_path ]
  then
    echo "No entry available."
  else
    vim $yesterday_path
  fi
}

function scrape {

	while IFS= read -r line; do
		if [ "${line:0:3}" = "[ ]" ]
		then
			echo $line >> $today_path
		fi

	done < $yesterday_path
  today
}

function today {
  # Check to see if todo directory exists
  if [ ! -d "$HOME/notes/todo" ]
  then
    echo "Error: directory ~/notes/todo does not exist."
  else
    vim $today_path
  fi
}

if [ $# -eq 0 ]
then
  today
else
  eval ${1}
fi

exit
